-- Chạy một lần trong Supabase SQL Editor.
alter table public.bookings add column if not exists cancellation_reason text;
alter table public.bookings add column if not exists refund_qr_url text;
alter table public.bookings add column if not exists cancellation_requested_at timestamptz;

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  homestay_id bigint not null references public.homestays(id) on delete cascade,
  customer_id uuid not null references auth.users(id) on delete cascade,
  rating int not null check (rating between 1 and 5),
  content text not null default '',
  created_at timestamptz not null default now(),
  unique (booking_id, customer_id)
);

alter table public.reviews enable row level security;
create policy "customers create own reviews" on public.reviews for insert
  with check (auth.uid() = customer_id);
create policy "reviews are public" on public.reviews for select using (true);

-- Tạo bucket này trong Storage nếu chưa có; policy giới hạn upload cho user đăng nhập.
insert into storage.buckets (id, name, public)
values ('user-attachments', 'user-attachments', true)
on conflict (id) do nothing;
create policy "authenticated upload attachments" on storage.objects for insert
  to authenticated with check (bucket_id = 'user-attachments');
create policy "public read attachments" on storage.objects for select
  using (bucket_id = 'user-attachments');
